package com.concavenp.artistrymuse.widget;

import android.appwidget.AppWidgetManager;
import android.appwidget.AppWidgetProvider;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;

import com.concavenp.artistrymuse.services.ArtistryAppWidgetService;

/**
 * Implementation of App Widget functionality.
 *
 * This class was generated by Android Studio through the Widget example and modified for use in
 * this app.
 */
public class ArtistryAppWidgetProvider extends AppWidgetProvider {

    @Override
    public void onUpdate(Context context, AppWidgetManager appWidgetManager, int[] appWidgetIds) {
        // Get all ids
        ComponentName thisWidget = new ComponentName(context, ArtistryAppWidgetProvider.class);
        int[] allWidgetIds = appWidgetManager.getAppWidgetIds(thisWidget);

        // Build the intent to call the service
        Intent intent = new Intent(context.getApplicationContext(), ArtistryAppWidgetService.class);
        intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, allWidgetIds);

        // Update the widgets via the service
        context.startService(intent);










//        for (int widgetId : allWidgetIds) {
//
//            final RemoteViews remoteViews = new RemoteViews(context.getPackageName(), R.layout.artistry_app_widget);
//
//            remoteViews.setTextViewText(R.id.favorited_textView, Integer.toString(42));
//            remoteViews.setTextViewText(R.id.views_textView, Integer.toString(43));
//            remoteViews.setTextViewText(R.id.rating_textView, String.format("%.1f", 7.777));
//
//            appWidgetManager.updateAppWidget(widgetId, remoteViews);
//        }
    }

    @Override
    public void onDeleted(Context context, int[] appWidgetIds) {
        // When the user deletes the widget, delete the preference associated with it.
//        for (int appWidgetId : appWidgetIds) {
//            ArtistryAppWidgetConfigureActivity.deleteTitlePref(context, appWidgetId);
//        }
    }

    @Override
    public void onEnabled(Context context) {
        // Enter relevant functionality for when the first widget is created
    }

    @Override
    public void onDisabled(Context context) {
        // Enter relevant functionality for when the last widget is disabled
    }

}

